name: infrareportes
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  google_maps_flutter: ^2.5.0
  geolocator: ^11.0.0
  permission_handler: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.2 # Paquete para generar íconos de la app
<<<<<<< HEAD
  
=======
>>>>>>> 89b9214cc4780b8f9d059668e30fade4ee77e2f3

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/avatar.png
    - assets/map_preview.png
